sudo: required
language: ruby
rvm:
  - 2.3.0
gemfile: tools/dev/Gemfile
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq debootstrap
script:
  - ./tools/ci.sh
  - sudo ./tools/ci.sh
