gemfile: tools/dev/Gemfile
before_install:
  - sudo gem install bundler
  - sudo bundle install --gemfile=tools/dev/Gemfile # install Gems for root as well
  - sudo apt-get update -qq
  - sudo apt-get install -qq debootstrap
script:
  - ./tools/ci.sh
  - sudo ./tools/ci.sh
