sudo: required
language: ruby
rvm:
  - 2.3.0
gemfile: tools/dev/Gemfile
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq rubygems ruby-bundler debootstrap
  - sudo bundle install --gemfile=tools/dev/Gemfile # install Gems for root as well
script:
  - ./tools/ci.sh
  - sudo ./tools/ci.sh
